import { createPatternTests } from '@bcew-monorepo/e2e';

createPatternTests( 'design-system-wordpress-theme', [
    'bc-gov-logo-dark',
    'bc-gov-logo-supported-light',
    'dswp-bullet-list',
    'dswp-call-to-action',
    'dswp-card-with-hyperlinks-list',
    'dswp-default-heading',
    'dswp-footer-with-territorial-acknowledgement',
    'dswp-h1-with-divider',
    'dswp-heading-with-paragraphs',
    'dswp-hero-image-with-title',
    'dswp-horizontal-card',
    'dswp-horizontal-card-large-img-left',
    'dswp-horizontal-card-large-img-no-shadow',
    'dswp-horizontal-card-large-img-right',
    'dswp-horizontal-card-reversed',
    'dswp-icon-with-excerpt',
    'dswp-image-text-flipped',
    'dswp-image-text',
    'dswp-information-contact-socials',
    'dswp-link-with-arrow',
    'dswp-post-pattern-horizontal-card-large-img-right',
    'dswp-secondary-hero-image-with-title',
    'dswp-team-pattern',
    'dswp-vertical-cards-with-icon',
    'dswp-vertical-cards',
] );
