<?php
/**
 * Integration tests for the CHEFS API client.
 *
 * @package bcew-chefs-embed
 */

namespace Bcgov\BcewChefsEmbed\Test;

use Bcgov\BcewChefsEmbed\ChefsClient;

/**
 * CHEFS client response handling.
 */
class ChefsClientTest extends \WP_UnitTestCase {

	/**
	 * HTTP callbacks registered by the current test.
	 *
	 * @var array<int, callable>
	 */
	private $http_callbacks = array();

	/**
	 * Remove HTTP stubs after each test.
	 *
	 * @return void
	 */
	public function tear_down() {
		foreach ( $this->http_callbacks as $callback ) {
			remove_filter( 'pre_http_request', $callback, 10 );
		}
		$this->http_callbacks = array();
		parent::tear_down();
	}

	/**
	 * A successful response returns the token and verifies the request details.
	 *
	 * @return void
	 */
	public function test_authenticate_returns_token_and_sends_basic_auth() {
		$form_id  = 'form-123';
		$api_key  = 'key-456';
		$requests = array();

		$this->add_http_callback(
			static function ( $pre, $args, $url ) use ( &$requests ) {
				$requests = array( $args, $url );
				return array(
					'body'     => '{"token":"token-789"}',
					'response' => array( 'code' => 200 ),
				);
			}
		);

		$result = ( new ChefsClient() )->authenticate( $form_id, $api_key );

		$this->assertSame(
			array(
				'success' => true,
				'token'   => 'token-789',
			),
			$result
		);
		$this->assertSame( 'https://submit.digital.gov.bc.ca/app/gateway/v1/auth/token/forms/form-123', $requests[1] );
		$this->assertSame( 'Basic ' . base64_encode( $form_id . ':' . $api_key ), $requests[0]['headers']['Authorization'] ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- Match the Basic Auth header generated by the client.
	}

	/**
	 * A CHEFS Bad formId response gets its specific internal code.
	 *
	 * @return void
	 */
	public function test_bad_form_id_response_is_classified() {
		$this->stub_response( 400, array( 'detail' => 'Bad formId "missing".' ) );

		$result = ( new ChefsClient() )->authenticate( 'missing', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'form_not_found',
            ),
            $result
        );
	}

	/**
	 * Credential-related statuses use the intentionally broad credential code.
	 *
	 * @return void
	 */
	public function test_credential_status_is_classified() {
		$this->stub_response( 403, array( 'detail' => 'Forbidden' ) );

		$result = ( new ChefsClient() )->authenticate( 'form', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'invalid_credentials',
            ),
            $result
        );
	}

	/**
	 * A 404 Bad formId response gets its specific internal code.
	 *
	 * @return void
	 */
	public function test_404_bad_form_id_response_is_classified() {
		$this->stub_response( 404, array( 'detail' => 'Bad formId "missing".' ) );

		$result = ( new ChefsClient() )->authenticate( 'missing', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'form_not_found',
            ),
            $result
        );
	}

	/**
	 * A transport failure does not expose the upstream error.
	 *
	 * @return void
	 */
	public function test_transport_failure_is_classified() {
		$this->add_http_callback(
			static function () {
				return new \WP_Error( 'http_request_failed', 'Connection failed' );
			}
		);

		$result = ( new ChefsClient() )->authenticate( 'form', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'request_failed',
            ),
            $result
        );
	}

	/**
	 * A successful response without a token is rejected.
	 *
	 * @return void
	 */
	public function test_malformed_success_response_is_classified() {
		$this->stub_response( 200, array( 'message' => 'ok' ) );

		$result = ( new ChefsClient() )->authenticate( 'form', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'invalid_response',
            ),
            $result
        );
	}

	/**
	 * A successful response with a non-string token is rejected.
	 *
	 * @return void
	 */
	public function test_non_string_token_response_is_classified() {
		$this->stub_response( 200, array( 'token' => array( 'unexpected' ) ) );

		$result = ( new ChefsClient() )->authenticate( 'form', 'key' );

		$this->assertSame(
            array(
				'success' => false,
				'code'    => 'invalid_response',
            ),
            $result
        );
	}

	/**
	 * Stub a WordPress HTTP response.
	 *
	 * @param int   $status HTTP status code.
	 * @param array $body   JSON response body.
	 * @return void
	 */
	private function stub_response( $status, array $body ) {
		$this->add_http_callback(
			static function () use ( $status, $body ) {
				return array(
					'body'     => wp_json_encode( $body ),
					'response' => array( 'code' => $status ),
				);
			}
		);
	}

	/**
	 * Register and track a test HTTP callback for exact teardown removal.
	 *
	 * @param callable $callback HTTP callback.
	 * @return void
	 */
	private function add_http_callback( callable $callback ) {
		$this->http_callbacks[] = $callback;
		add_filter( 'pre_http_request', $callback, 10, 3 );
	}
}
