name: Release Subproject and Update packages.json
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Project to release'
        required: true
        type: choice
        options:
          - bcew-blocks
          - bcew-belleville-terminal
          - bcew-theme-2
          - bcew-ticorp
          - bcew-document-repository
          - bcew-chefs-embed
      version:
        description: 'Version to release (for example: 1.2.3)'
        required: true
        type: string
      is_prerelease:
        description: 'Is this a pre-release?'
        type: boolean

concurrency:
  group: composer-repo-update
  cancel-in-progress: false

jobs:
  build-and-deploy:
    permissions:
       contents: write
       pages: write
       id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
            client-id: ${{ vars.GH_APP_CLIENT_ID }}
            private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
            version: 10
            cache: true

      - name: Setup Node.js 24
        uses: actions/setup-node@v6.4.0
        with:
            node-version: 24
            cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Parse Inputs
        id: vars
        shell: bash
        env:
          NAME: ${{ inputs.name }}
          VERSION: ${{ inputs.version }}
          IS_PRERELEASE: ${{ inputs.is_prerelease }}
        run: |
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version_normalized=$VERSION" >> $GITHUB_OUTPUT
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "project_path=$(pnpm nx show project $NAME --json | jq -r .root)" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "tag=$NAME/v$VERSION" >> $GITHUB_OUTPUT
          echo "asset_name=$NAME-$VERSION.zip" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: pnpm nx run ${{ steps.vars.outputs.name }}:composer-install

      - name: Nx Build
        run: pnpm nx run ${{ steps.vars.outputs.name }}:build

      - name: Update versions and zip build artifacts
        env:
          ASSET_NAME: ${{ steps.vars.outputs.asset_name }}
        run: |
            bash .github/scripts/prepare-release-zip.sh \
              "${{ steps.vars.outputs.project_path }}" \
              "${{ steps.vars.outputs.name }}" \
              "${{ steps.vars.outputs.version_normalized }}"

      - name: Create tag
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
            exit 1
          else
            SHA=$(git rev-parse HEAD)

            gh api \
                repos/${{ github.repository }}/git/refs \
                --method POST \
                -f ref="refs/tags/$TAG" \
                -f sha="$SHA"
          fi

      - name: Generate changelog
        id: build_changelog
        if: ${{ inputs.tag_name != '' }}
        uses: mikepenz/release-changelog-builder-action@c9bcd8238b6f41e05561348339429d360b1c0247 # v6.2.2
        with:
            includeOnlyPaths: ${{ steps.vars.outputs.project_path }}
            ignorePreReleases: "false"
            # Todo: Automatically detect previous tag, rather than hardcoding.
            # This is the initial commit of the repository, so all PRs will be included in the changelog until we can set the fromTag dynamically.
            fromTag: "d6725a2e0088842eaf5636847efc3a77d60564a5"
            toTag: ${{ steps.vars.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: ${{ steps.vars.outputs.project_path }}/${{ steps.vars.outputs.asset_name }}
          tag_name: ${{ steps.vars.outputs.tag }}
          prerelease: ${{ steps.vars.outputs.is_prerelease }}
          body: ${{steps.build_changelog.outputs.changelog}}

      - name: Update packages.json
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ steps.vars.outputs.tag }}
          VERSION: ${{ steps.vars.outputs.version }}
          PROJECT_PATH: ${{ steps.vars.outputs.project_path }}
          ASSET_NAME: ${{ steps.vars.outputs.asset_name }}
        run: |
          curl --tlsv1.2 -sSf https://${{ github.repository_owner }}.github.io/bcew-monorepo/packages.json -o packages.json || echo '{"packages":{}}' > packages.json

          mkdir public

          php .github/scripts/update-packages.php

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: ./public
          keep_files: true
